{% set name = "descent" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/descent/archive/{{ version }}.tar.gz
  sha256: 6071fb540facff69c74cf2f65cad2edb79bf4d23de0435c74fbf885a6d611e8f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - versioningit
  run:
    - python >=3.10
    - smee >=0.8.0
    - pydantic >=2
    - pyarrow
    - datasets
    - scipy
    - pytorch
test:
  imports:
    - descent

about:
  home: https://github.com/SimonBoothroyd/descent
  summary: 'Optimize classical force field parameters against reference data'
  description: |
    A framework that aims to offer a modern API for training classical force field parameters 
    (either from a traditional format such as SMIRNOFF or from some ML model) against reference 
    data using pytorch.
  license: MIT AND BSD-3-Clause
  license_file:
    - LICENSE
    - LICENSE_3RD_PARTY
  doc_url: https://github.com/SimonBoothroyd/descent
  dev_url: https://github.com/SimonBoothroyd/descent

extra:
  recipe-maintainers:
    - SimonBoothroyd
